name = "sharex-r2-cloudflare-workers"
type = "javascript"
account_id = "505b1854fb3fb9bce6eaba5695228c43"
workers_dev = true
route = "blcdn.burnsland.com/*"
zone_id = "87b6e575cfe41eda3850b2077e93ecb5"
compatibility_date = "2022-04-22"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "blcdn"
preview_bucket_name="blcdn"
binding = "R2_BUCKET"